### ISSUE TITLE
Error as BootstrapVueNextResolver not found (BootstrapVue3Resolver exists)

### ISSUE THREAD

**Issue by JochenSeifarth** [bootstrap-vue/bootstrap-vue-next#883]
BootstrapVue**Next**Resolver as described on [https://bootstrap-vue.github.io/bootstrap-vue-next/getting-started/#installation-vue-js)](https://bootstrap-vue.github.io/bootstrap-vue-next/getting-started/#installation-vue-js)
cannot be found. There is however a BootstrapVue**3**Resolver in
https://github.com/antfu/unplugin-vue-components/blob/main/src/core/resolvers/bootstrap-vue-**3**.ts
but no 
https://github.com/antfu/unplugin-vue-components/blob/main/src/core/resolvers/bootstrap-vue-**next**.ts

I am using the latest version unplugin-vue-components@0.22.12

To reproduce, follow the instruction on [https://bootstrap-vue.github.io/bootstrap-vue-next/getting-started/#installation-vue-js)](https://bootstrap-vue.github.io/bootstrap-vue-next/getting-started/#installation-vue-js) and run 
```
user@host:~/vue3/vite-project$ npm run dev

> vite-project@0.0.0 dev
> vite

failed to load config from /home/user/vue3/vite-project/vite.config.ts
error when starting dev server:
file:///home/user/vue3/vite-project/vite.config.ts.timestamp-1673807439426.mjs:5
import { BootstrapVueNextResolver } from "file:///home/user/vue3/vite-project/node_modules/unplugin-vue-components/dist/resolvers.mjs";
         ^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: The requested module 'file:///home/user/vue3/vite-project/node_modules/unplugin-vue-components/dist/resolvers.mjs' does not provide an export named 'BootstrapVueNextResolver'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadConfigFromBundledFile (file:///home/user/vue3/vite-project/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:62084:21)
    at async loadConfigFromFile (file:///home/user/vue3/vite-project/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:61969:28)
    at async resolveConfig (file:///home/user/vue3/vite-project/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:61590:28)
    at async createServer (file:///home/user/vue3/vite-project/node_modules/vite/dist/node/chunks/dep-5e7f419b.js:60910:20)
    at async CAC.<anonymous> (file:///home/user/vue3/vite-project/node_modules/vite/dist/node/cli.js:729:24)

```

**Comment by VividLemon** [comment]
https://github.com/antfu/unplugin-vue-components/pull/587

**Comment by hussainfrotan** [comment]
I faced the same issue after moving to bootstrap-vue-next from bootstrap-vue-3

**Comment by adiramardiani** [comment]
this issue is important, because written on documentation
but after 2 weeks has no progress of merge, I see the commit on unplugin-vue-component is 1 day ago
I just want to remind the maintainers to not ignore the pull request @VividLemon

**Comment by VividLemon** [comment]
Anyone is capable of replicating the code I had written over there as a temporary measure. 
![image](https://user-images.githubusercontent.com/31498096/215335313-feb02af7-9c79-4770-9feb-5dbfe5fc1def.png)

**Comment by danielvy** [comment]
@VividLemon 

In line 31, I think it needs to be lowercase "v" for directives to work.

```
return { name: `v${name}`, from: 'bootstrap-vue-next' }
```

**Comment by VividLemon** [comment]
> @VividLemon
> 
> In line 31, I think it needs to be lowercase "v" for directives to work.
> 
> ```
> return { name: `v${name}`, from: 'bootstrap-vue-next' }
> ```

I'll have to review the code a bit further. The code was originally copied from the original bootstrap vue resolver, but I don't think its compatibility (the regex statement seems incompatible)
