### ISSUE TITLE
nuxi typecheck reports error for nuxt.ts

### ISSUE THREAD

**Issue by duc2019** [bootstrap-vue/bootstrap-vue-next#940]
Version: 0.7.3

Steps to reproduce: 

- Create a nuxt 3 project
- Include bootstrap-vue-next 0.7.3
- Execute "nuxi typecheck"

Error message:

```
Nuxi 3.2.2                                                                                                                                  06:01:56
node_modules/bootstrap-vue-next/nuxt.ts:62:14 - error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'string | number | symbol'.
  No index signature with a parameter of type 'string' was found on type 'string | number | symbol'.

62     (el) => ((internalDefaults as unknown as keyof T)[el] = all)
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/bootstrap-vue-next/nuxt.ts:62


 ERROR  Command failed with exit code 2: vue-tsc --noEmit                                                                                   06:03:03

  at makeError (node_modules/nuxi/dist/shared/nuxi.a8fc08e2.mjs:623:11)
  at handlePromise (node_modules/nuxi/dist/shared/nuxi.a8fc08e2.mjs:1031:26)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Object.invoke (node_modules/nuxi/dist/chunks/typecheck.mjs:43:7)
  at async _main (node_modules/nuxi/dist/cli.mjs:51:20)
```

Change `internalDefaults as unknown as keyof T` to `internalDefaults as any` will fix this error.

**Comment by VividLemon** [comment]
Will be fixed in a breaking change 0.9.0
(After 0.8.0, the nuxt.ts file will be moved to a new package - @bootstrap-vue-next/nuxt)
