### ISSUE TITLE
Docs show white page.

### ISSUE THREAD

**Issue by YosefOberlander** [bootstrap-vue/bootstrap-vue-next#980]
When trying to visit the the docs at https://bootstrap-vue.github.io/bootstrap-vue-next/ all you see is a blank page.

OS: macOS Ventura
Browser: Chrome, Safari, Firefox

**Comment by Kenvdb** [comment]
Yes same here.

**Comment by Triztan** [comment]
If you go to a page directly, it's exactly the same:
https://bootstrap-vue.github.io/bootstrap-vue-next/components/Modal.html
Console error:
```
p.8a345480.js:1 Error: useThemeLocaleData() is called without provider.
    at Iv (app.8a345480.js:8:5415)
    at Of (app.8a345480.js:8:14364)
    at f_ (app.8a345480.js:8:12478)
    at Object.setup (app.8a345480.js:8:14813)
    at setup (app.8a345480.js:12:94767)
    at ln (app.8a345480.js:1:16801)
    at Bh (app.8a345480.js:1:54029)
    at Mh (app.8a345480.js:1:53814)
    at z (app.8a345480.js:1:43451)
    at h (app.8a345480.js:1:37837)
```

**Comment by YosefOberlander** [comment]
I ended up cloning the repo and running it locally to get the docs work l.
